# Generated by Django 4.2.7 on 2024-06-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='account_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='callback_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
